name: peyekk
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  carousel_slider: ^4.2.1
  intl: ^0.19.0
  firebase_core: ^3.1.0
  firebase_database: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/background.jpg
    - assets/images/logodashboard.png
    - assets/images/background1.jpg

  fonts:
    - family: PaytoneOne
      fonts:
        - asset: assets/fonts/PaytoneOne-Regular.ttf
